## makeCacheMatrix generates the object with the necessary functions
## see test case cachetest() for the calling sequence


makeCacheMatrix <- function(x = matrix()) {
        im <- NULL
        setm <- function(y) {
                x <<- y
                im <<- NULL
        }
        getm <- function() x
        setim <- function(ivm) im <<- ivm
        getim <- function() im
        list(setm = setm, getm = getm,
             setim = setim,
             getim = getim)
}

## CacheSolve utilzes the object generated by makeCacheMatrix to do the job
CacheSolve <- function(x, ...) {
        im <- x$getim()
        if(!is.null(im)) {
                message("Getting cached data")
                return(im)
        }
        data <- x$getm()
        im <- solve(data)
        x$setim(im)
        im
}

# test case for verification
cacheTest <- function(){
	my_matrix <- matrix(c(1,11,3,21,5,31,7,17,9,19,51,12,13,14,15,121), nrow = 4, ncol = 4)
	mcmatrix <-makeCacheMatrix(my_matrix)
	infm <- CacheSolve(mcmatrix)
	print(infm)
	infm <- CacheSolve(mcmatrix)
	print(infm)
	
	s_matrix <- matrix(1:4, nrow = 2, ncol = 2)
	mcmatrix <-makeCacheMatrix(s_matrix)
	infm <- CacheSolve(mcmatrix)
	print(infm)
	infm <- CacheSolve(mcmatrix)
	print(infm)
}
